backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: public/images
public_folder: /images
# publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Projects"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug:
      encoding: "ascii"
      clean_accents: true
      sanitize_replacement: "_"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: Main Processes
        label_singular: "Main Process"
        name: "processes"
        widget: list
        summary: "{{fields.process}}"
        field:
          label: Main Process
          name: process
          widget: relation
          collection: "meta"
          file: "processes"
          searchFields:
            - "processes.*.name"
          displayFields:
            - "processes.*.name"
          valueField: "processes.*.slug"

      - label: Sub Processes
        label_singular: "Sub Process"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Sub Process
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "processes"
        label: "Main Processes"
        file: "meta/processes.yml"
        description: "List of main processes"
        fields:
          - name: processes
            label: Main Processes
            label_singular: "Main Process"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the process"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Process name for displaying on the site"

      - name: "tags"
        label: "Sub Processes"
        file: "meta/tags.yml"
        description: "List of processes"
        fields:
          - name: tags
            label: Sub Processes
            label_singular: "Sub Process"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the process"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Process name for displaying on the site"

  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
